name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --dev

      - name: Run test
        run: ./vendor/bin/phpunit
        continue-on-error: true

      - name: Run phpcs
        run: ./vendor/bin/phpcs --standard=PSR12 --encoding=utf-8 src tests
        continue-on-error: true
